name: Generate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Generate
      run: xvfb-run --auto-servernum ./gradlew runClient

    - name: Commit & Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git checkout -B --orphan generated
        git ls-files | xargs -r git rm || true
        git clean -fd
        git commit --allow-empty -m "Clean generated branch"

        cp -r ./run/generated/* .
        ls -la

        git add .
        git commit -m "Auto-generated at $(date +'%Y-%m-%d %H:%M')"
        git push origin generated --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
